/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cyberpunk_desk.glb 
Author: Cisco (https://sketchfab.com/Ciscow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-desk-8bc4ca48b2e244ff8b5ba714a2ec1963
Title: Cyberpunk Desk
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { getAssetPath } from '../../utils/getAssetPath'

export function Cyber(props) {
  const { nodes, materials } = useGLTF(getAssetPath('/models/cyberpunk_desk.glb'))
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['1041']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['1042']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['1043']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['1053']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['1054']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['1055']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['1045']} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('/models/cyberpunk_desk.glb'))
