/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 f16.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { getAssetPath } from '../../utils/getAssetPath'

export function F16(props) {
  const { nodes, materials } = useGLTF(getAssetPath('/models/f16.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -3.931]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Main_LOD1_00_low004.geometry} material={materials.FA_N26_LOD5} position={[0, -0.039, 0]} />
        <mesh geometry={nodes.Main_LOD0_00_low004.geometry} material={materials.FA_N26_LOD4} position={[0, -0.039, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('/models/f16.glb')
