/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ai_figure.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Figure(props) {
  const { nodes, materials } = useGLTF('/models/ai_figure.glb')
  const groupRef = useRef()
  
  // Rotate the figure slowly on the Y-axis
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005
    }
  })
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.material.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/ai_figure.glb')
