/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.glb 
*/

import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { getAssetPath } from '../../utils/getAssetPath'

export function Spaceship(props) {
  const { nodes, materials } = useGLTF(getAssetPath('/models/spaceship.glb'))
  const groupRef = useRef()
  
  // Set initial rotation to 180 degrees on mount
  useEffect(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y = Math.PI
    }
  }, [])
  
  // Rotate the spaceship slowly on the Y-axis
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005
    }
  })
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01} rotation={[-(Math.PI / 5), -(Math.PI / 6), 0]}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
          <mesh geometry={nodes.Cube009_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube009_Material004_0.geometry} material={materials['Material.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('/models/spaceship.glb'))
